package markdown

import (
	"regexp"
	"strings"
)

// ConvertColBlocksInMarkdown converts ::: col ... ::: blocks to blockquotes with COLBLOCK markers
// that goldmark can process. The markers are later converted to <div class="col"> in HTML post-processing.
func ConvertColBlocksInMarkdown(md string) string {
	lines := strings.Split(md, "\n")
	var result []string
	var inFencedCodeBlock bool
	var inIndentedCodeBlock bool

	i := 0
	for i < len(lines) {
		line := lines[i]
		trimmed := strings.TrimSpace(line)

		// Track fenced code blocks
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFencedCodeBlock = !inFencedCodeBlock
			result = append(result, line)
			i++
			continue
		}

		// Track indented code blocks
		if len(line) > 0 && strings.HasPrefix(line, "    ") && strings.TrimSpace(line) != "" {
			inIndentedCodeBlock = true
		} else if inIndentedCodeBlock {
			if strings.TrimSpace(line) == "" && i+1 < len(lines) && (len(lines[i+1]) == 0 || !strings.HasPrefix(lines[i+1], "    ")) {
				inIndentedCodeBlock = false
			} else if len(line) > 0 && !strings.HasPrefix(line, "    ") {
				inIndentedCodeBlock = false
			}
		}

		if inFencedCodeBlock || inIndentedCodeBlock {
			result = append(result, line)
			i++
			continue
		}

		if trimmed == "::: col" || trimmed == ":::col" {
			// Find closing :::
			endIdx := -1
			for j := i + 1; j < len(lines); j++ {
				if strings.TrimSpace(lines[j]) == ":::" {
					endIdx = j
					break
				}
			}

			if endIdx != -1 {
				var out strings.Builder
				// Trailing ">" blank line keeps the marker in its own paragraph so
				// it does not merge with the first content line when ::: col is not
				// followed by a blank line (which would leak an orphan </p>).
				out.WriteString("> **COLBLOCK**\n>\n")
				for j := i + 1; j < endIdx; j++ {
					if strings.TrimSpace(lines[j]) != "" {
						out.WriteString("> " + lines[j] + "\n")
					} else {
						out.WriteString(">\n")
					}
				}
				result = append(result, strings.TrimSuffix(out.String(), "\n"))
				// Emit a blank line after the block so that consecutive col blocks
				// (e.g. a closing ::: immediately followed by ::: col) are not merged
				// into a single blockquote by goldmark. Without this separation the
				// HTML post-processor sees one blockquote containing two COLBLOCK
				// markers, leaks the literal "COLBLOCK" text, and collapses the
				// columns into one div.
				result = append(result, "")
				i = endIdx + 1
				continue
			}
		}

		result = append(result, line)
		i++
	}

	return strings.Join(result, "\n")
}

// colBlockStartRE matches the opening of a COLBLOCK blockquote (the <blockquote> tag
// plus the COLBLOCK marker paragraph) generated by ConvertColBlocksInMarkdown.
var colBlockStartRE = regexp.MustCompile(`(?s)<blockquote[^>]*>\s*(?:<p[^>]*>\s*)?<strong>COLBLOCK</strong>\s*(?:</p>)?\s*`)

// ConvertColBlocksInHTML converts COLBLOCK blockquotes to <div class="col"> elements.
// It scans for the matching </blockquote> by tracking blockquote nesting depth so that
// a column whose content contains a nested blockquote (e.g. a markdown "> quote") is not
// truncated at the inner closing tag.
func ConvertColBlocksInHTML(htmlContent string) string {
	const closeTag = "</blockquote>"
	var out strings.Builder
	pos := 0
	for {
		loc := colBlockStartRE.FindStringIndex(htmlContent[pos:])
		if loc == nil {
			out.WriteString(htmlContent[pos:])
			break
		}
		start := pos + loc[0]        // position of the opening <blockquote
		contentStart := pos + loc[1] // position just after the COLBLOCK marker
		out.WriteString(htmlContent[pos:start])

		// Walk forward from the opening tag, balancing <blockquote>/</blockquote>.
		depth := 0
		j := start
		closeStart := -1
		for j < len(htmlContent) {
			if strings.HasPrefix(htmlContent[j:], "<blockquote") {
				depth++
				j += len("<blockquote")
			} else if strings.HasPrefix(htmlContent[j:], closeTag) {
				depth--
				if depth == 0 {
					closeStart = j
					break
				}
				j += len(closeTag)
			} else {
				j++
			}
		}

		if closeStart == -1 {
			// Unbalanced markup: leave the remainder untouched.
			out.WriteString(htmlContent[start:])
			break
		}

		content := strings.TrimSpace(htmlContent[contentStart:closeStart])
		out.WriteString(`<div class="col">` + content + `</div>`)
		pos = closeStart + len(closeTag)
	}
	return out.String()
}
