package markdown

import (
	"regexp"
	"strings"
)

// ConvertColBlocksInMarkdown converts ::: col ... ::: blocks to blockquotes with COLBLOCK markers
// that goldmark can process. The markers are later converted to <div class="col"> in HTML post-processing.
func ConvertColBlocksInMarkdown(md string) string {
	lines := strings.Split(md, "\n")
	var result []string
	var inFencedCodeBlock bool
	var inIndentedCodeBlock bool

	i := 0
	for i < len(lines) {
		line := lines[i]
		trimmed := strings.TrimSpace(line)

		// Track fenced code blocks
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFencedCodeBlock = !inFencedCodeBlock
			result = append(result, line)
			i++
			continue
		}

		// Track indented code blocks
		if len(line) > 0 && strings.HasPrefix(line, "    ") && strings.TrimSpace(line) != "" {
			inIndentedCodeBlock = true
		} else if inIndentedCodeBlock {
			if strings.TrimSpace(line) == "" && i+1 < len(lines) && (len(lines[i+1]) == 0 || !strings.HasPrefix(lines[i+1], "    ")) {
				inIndentedCodeBlock = false
			} else if len(line) > 0 && !strings.HasPrefix(line, "    ") {
				inIndentedCodeBlock = false
			}
		}

		if inFencedCodeBlock || inIndentedCodeBlock {
			result = append(result, line)
			i++
			continue
		}

		if trimmed == "::: col" || trimmed == ":::col" {
			// Find closing :::
			endIdx := -1
			for j := i + 1; j < len(lines); j++ {
				if strings.TrimSpace(lines[j]) == ":::" {
					endIdx = j
					break
				}
			}

			if endIdx != -1 {
				var out strings.Builder
				out.WriteString("> **COLBLOCK**\n")
				for j := i + 1; j < endIdx; j++ {
					if strings.TrimSpace(lines[j]) != "" {
						out.WriteString("> " + lines[j] + "\n")
					} else {
						out.WriteString(">\n")
					}
				}
				result = append(result, strings.TrimSuffix(out.String(), "\n"))
				i = endIdx + 1
				continue
			}
		}

		result = append(result, line)
		i++
	}

	return strings.Join(result, "\n")
}

// colBlockRE matches blockquotes with COLBLOCK marker generated by ConvertColBlocksInMarkdown.
var colBlockRE = regexp.MustCompile(`(?s)<blockquote[^>]*>\s*(?:<p[^>]*>\s*)?<strong>COLBLOCK</strong>\s*(?:</p>)?\s*(.*?)</blockquote>`)

// ConvertColBlocksInHTML converts COLBLOCK blockquotes to <div class="col"> elements.
func ConvertColBlocksInHTML(htmlContent string) string {
	return colBlockRE.ReplaceAllStringFunc(htmlContent, func(match string) string {
		submatches := colBlockRE.FindStringSubmatch(match)
		if len(submatches) < 2 {
			return match
		}
		content := strings.TrimSpace(submatches[1])
		return `<div class="col">` + content + `</div>`
	})
}
